[workspace]
resolver = "3"
members = ["crates/oxid-core", "crates/oxid-daemon", "crates/oxid-cli"]
default-members = ["crates/oxid-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
description = "Ephemeral environments that breathe. Ferrous performance, invisible footprint."
publish = false

[workspace.dependencies]
oxid-core = { path = "crates/oxid-core" }
thiserror = "2.0"
trait-variant = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3", features = ["serde", "macros", "formatting", "parsing"] }
toml = "0.8"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "net", "time"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "migrate", "macros"] }
bollard = "0.17"
tar = "0.4"
bytes = "1"
git2 = { version = "0.20", default-features = false, features = ["https", "vendored-libgit2", "vendored-openssl"] }
axum = "0.8"
futures-util = "0.3"
tower = { version = "0.5", features = ["util"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
aes-gcm = "0.10"
rand = "0.8"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"