[package]
name = "oxid-daemon"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "oxidd"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
oxid-core.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tokio.workspace = true
sqlx.workspace = true
bollard.workspace = true
tar.workspace = true
bytes.workspace = true
git2.workspace = true
axum.workspace = true
futures-core.workspace = true
futures-util.workspace = true
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
aes-gcm.workspace = true
rand.workspace = true
url.workspace = true
yaml-rust2 = "0.12.0"

[dev-dependencies]
tower.workspace = true
tempfile = "3"
time.workspace = true
